// Commit types following Conventional Commits specification
export type CommitType = "feat" | "fix" | "refactor" | "test" | "docs" | "chore" | "perf" | "ci" | "style" | "build" | "revert";

// Keywords that suggest a particular commit type
export const TYPE_KEYWORDS: Record<CommitType, string[]> = {
  feat: ["feature", "implement", "new", "create", "introduce", "support"],
  fix: ["fix", "bug", "error", "crash", "issue", "resolve", "handle", "patch", "correct", "repair"],
  refactor: ["refactor", "restructure", "reorganize", "simplify", "clean", "extract", "move", "rename", "split", "merge"],
  test: ["test", "spec", "expect", "assert", "mock", "stub", "coverage"],
  docs: ["readme", "documentation", "comment", "jsdoc", "license", "changelog"],
  chore: ["dependency", "upgrade", "bump", "version", "config", "setup", "init"],
  perf: ["performance", "optimize", "speed", "cache", "lazy", "fast", "slow", "memory", "benchmark"],
  ci: ["workflow", "pipeline", "deploy", "action", "jenkins", "travis", "circle"],
  style: ["format", "indent", "whitespace", "semicolon", "lint", "prettier", "eslint"],
  build: ["build", "compile", "bundle", "webpack", "vite", "rollup", "esbuild"],
  revert: ["revert", "undo", "rollback"],
};

// File patterns that map to commit types
export const FILE_TYPE_PATTERNS: Array<{ pattern: RegExp; type: CommitType }> = [
  { pattern: /\.(test|spec)\.(ts|tsx|js|jsx|py|go|rs)$/, type: "test" },
  { pattern: /__tests__\//, type: "test" },
  { pattern: /\.(md|txt|rst|adoc)$/, type: "docs" },
  { pattern: /^docs\//, type: "docs" },
  { pattern: /^README/, type: "docs" },
  { pattern: /^LICENSE/, type: "docs" },
  { pattern: /^CHANGELOG/, type: "docs" },
  { pattern: /^\.github\/(workflows|actions)\//, type: "ci" },
  { pattern: /^\.gitlab-ci/, type: "ci" },
  { pattern: /^Jenkinsfile/, type: "ci" },
  { pattern: /^\.circleci\//, type: "ci" },
  { pattern: /^(package|composer|Gemfile|Cargo|go\.(mod|sum)|requirements)/, type: "chore" },
  { pattern: /^package-lock\.json$/, type: "chore" },
  { pattern: /^yarn\.lock$/, type: "chore" },
  { pattern: /^pnpm-lock\.yaml$/, type: "chore" },
  { pattern: /\.(css|scss|sass|less|styl)$/, type: "style" },
  { pattern: /^(webpack|vite|rollup|esbuild|tsup)\.config/, type: "build" },
  { pattern: /^Dockerfile/, type: "build" },
  { pattern: /^docker-compose/, type: "build" },
];

// File path patterns that map to scopes
export const SCOPE_PATTERNS: Array<{ pattern: RegExp; scope: string }> = [
  { pattern: /^src\/api\//, scope: "api" },
  { pattern: /^src\/components\//, scope: "ui" },
  { pattern: /^src\/pages\//, scope: "pages" },
  { pattern: /^src\/hooks\//, scope: "hooks" },
  { pattern: /^src\/utils\//, scope: "utils" },
  { pattern: /^src\/lib\//, scope: "lib" },
  { pattern: /^src\/services\//, scope: "services" },
  { pattern: /^src\/middleware\//, scope: "middleware" },
  { pattern: /^src\/models\//, scope: "models" },
  { pattern: /^src\/routes\//, scope: "routes" },
  { pattern: /^src\/controllers\//, scope: "controllers" },
  { pattern: /^src\/views\//, scope: "views" },
  { pattern: /^src\/store\//, scope: "store" },
  { pattern: /^src\/styles\//, scope: "styles" },
  { pattern: /^src\/types\//, scope: "types" },
  { pattern: /^src\/config\//, scope: "config" },
  { pattern: /^src\/database\//, scope: "db" },
  { pattern: /^src\/auth\//, scope: "auth" },
  { pattern: /^tests?\//, scope: "tests" },
  { pattern: /^e2e\//, scope: "e2e" },
];

// Verbs to extract from diff content for subject generation
export const ACTION_VERBS: Record<string, string> = {
  add: "add",
  added: "add",
  adding: "add",
  create: "add",
  created: "add",
  new: "add",
  implement: "implement",
  implemented: "implement",
  remove: "remove",
  removed: "remove",
  delete: "remove",
  deleted: "remove",
  update: "update",
  updated: "update",
  change: "update",
  changed: "update",
  modify: "update",
  modified: "update",
  fix: "fix",
  fixed: "fix",
  handle: "handle",
  handled: "handle",
  improve: "improve",
  improved: "improve",
  refactor: "refactor",
  refactored: "refactor",
  rename: "rename",
  renamed: "rename",
  move: "move",
  moved: "move",
  replace: "replace",
  replaced: "replace",
  simplify: "simplify",
  simplified: "simplify",
  optimize: "optimize",
  optimized: "optimize",
  integrate: "integrate",
  integrated: "integrate",
  configure: "configure",
  configured: "configure",
  enable: "enable",
  enabled: "enable",
  disable: "disable",
  disabled: "disable",
  migrate: "migrate",
  migrated: "migrate",
  upgrade: "upgrade",
  upgraded: "upgrade",
  deprecate: "deprecate",
  deprecated: "deprecate",
};
